### ISSUE TITLE
Name highlighting within words

### ISSUE THREAD

**Issue by Brotherbag** [TreffnonX/TakWeb#11]
Every time anyone uses my name in a word my name highlights, and my name is in lots of words, eg re**ally**, fin**ally**, tot**ally** etc...

**Comment by TreffnonX** [comment]
that one is on me... I gave chaitu the solution that he currently uses. But it was incomplete. It should be fine with the next update, given he takes it.

**Comment by Brotherbag** [comment]
It's actually only a problem on the fork, not on playtak.

**Comment by Brotherbag** [comment]
You've fixed it.
