### ISSUE TITLE
Pull commit 951dfb0 from chaitu236/TakWeb

### ISSUE THREAD

**Issue by chaitu236** [TreffnonX/TakWeb#14]
Hey Treff can you pull [this](https://github.com/chaitu236/TakWeb/commit/951dfb0b3d0935e9ea5160a68d25a96e2359fd3d) commit into your fork?

This enables TakWeb to keep working with latest websockify which [removed text mode](https://github.com/novnc/websockify/issues/365#issuecomment-432270758).

I'll wait on the websockify upgrade until this is pulled.

BTW, I tried doing an actual pull request but Github is weird with main->fork pull requests and I couldn't figure it out.

Thanks
kakaburra

PS: I did verify that the changes work on your fork.

**Comment by TreffnonX** [comment]
Hello Chaitu. Will do, but I am without laptop this week, and can only pull it next sunday, as I am unable to merge here. You can Do the upgrade server side. People who use the fork will need to use the original page for a bit then. I still have to fix an issue with the selection anyway, and want to do that along the line. Thank you for the heads up and I hope you are well :) sincerely Treff

**Comment by chaitu236** [comment]
Hello Treff, thats alright I still have to take care of some things before doing the upgrade so I can wait until next Sunday no problem. Thank you, hope you're well.

**Comment by TreffnonX** [comment]
Hello Chaitu, I solved it vie a manual merge, and just copied the required lines, as I also saw no reasonable way to do this.
After seeing the modifications, I wonder why they would withdraw string-support though, but that is another topic.
Thank you again for giving me a heads up!

**Comment by chaitu236** [comment]
Awesome. No problem!
